close.js
index.html

PR: https://github.com/brandon1024/find/issues/8

Added close extension functionality to close button

---

extension.css
index.html

PR: https://github.com/brandon1024/find/issues/12

F12 improve look of search bar

---

extension.css

PR: https://github.com/brandon1024/find/issues/16

F16 decrease Margin of search bar

---

manifest.json

PR: https://github.com/brandon1024/find/issues/18

Set 3 needed icon sizes based of 1 512x512 icon

---

index/extension.css

Ticket: https://github.com/brandon1024/find/issues/26

added reference to /resources folder

---

index/extension.css

Ticket: https://github.com/brandon1024/find/issues/30

Added margin to left side of body

---

index/index.html

Ticket: https://github.com/brandon1024/find/issues/33

Added tool tip title to button

---

popup/popup.js

Added listener to handle extension keyboard shortcuts

---

LICENSE

Added a license to our repository to protect our works.

Created GNU General Public License

---

backend/backend.js

Added index wrapping

---

backend/backend.js
content/content.js
content/highlighter.js

Fixes: https://github.com/brandon1024/find/issues/75
This PR addresses several performance and bug fixes. Here is what is changed:
- Refactored `highlight_next` and `highlight_previous` actions into `highlight_seek`
- Added offset to scrolling to ensure highlighted text is not hidden behind banners
- Performance improvements in content.js to first check style attributes before computing style
- Create `tags` object in `highlighter.js` to eliminate the need to construct new markup strings with every iteration
- Dropped global flag on regex, as it was causing the RegExp.exec() function to finish prematurely (due to the fact that `groupText` is being modified, the lastIndex field of RegExp object was causing issues)
- Ensure markup is injected when transitioning between text groups
- Ensure …

Performance Improvements and Bug Fixes

---

manifest.json

Small changes to manifest to prepare for next release.

V1.2.0 Pre Release Prep

---

manifest.json

Small changes to manifest to prepare for next release.

V1.2.1 Pre Release Prep

---

content/highlighter.js

Added an outer boundary flag to the charMap in the highlighter flow to ensure subsequent occurrences of a regular expression are separated.

Subsequent Occurrences of Regex Improperly Highlighted

---

README.md
manifest.json

Small changes to manifest to prepare for next release.

V1.2.2 Pre Release Prep

---

popup/popup.js

Added event listener to extension popup body, requesting search field focus on click event.

Clicking Popup Body Requests Focus From Search Field

---

popup/popup.js

Prevented exception from being thrown by adding null check on data.payload.

Exception Thrown After Install 

---

manifest.json

Changed version number in manifest to reflect new version.

V1.2.3 Pre-Release Prep

---

backend/backend.js
content/content.js
content/highlighter.js
manifest_firefox.json
popup/extension.css
popup/popup.html
popup/popup.js

- Added `browser.xxx` namespace and `chrome.xxx` namespace to the window object.
- The appropriate namespace is chosen depending on which namespace responds to being invoked.
- Need to create separate manifest file supported by Firefox, and debug font style issue.
https://www.davrous.com/2016/12/07/creating-an-extension-for-all-browsers-edge-chrome-firefox-opera-brave/

Port Extension to Firefox

---

manifest.json
manifest_firefox.json

- Updated Manifest version from 1.2.3 to 1.3.0

HOTIFX: Updated Manifest

---

README.md
manifest_firefox.json

Minor updates to README and firefox manifest.

F readme manifest updates

---

backend/backend.js
content/highlighter.js

- Fixes an error in scrollIntoView() caused by a miscalculated index in backend
- Fixes an error in the highlighter that caused parts of the web page to be removed

Options Bug Fixes

---

manifest.json
manifest_firefox.json

V1.3.1 Pre Release Prep

---

popup/popup.js

- Removed exception for 'chrome://newtab'
- Added check for 'https://google.***/_/chrome/newtab'

Exclude New Tab URL

---

README.md
backend/backend.js
content/content.js
content/highlighter.js
popup/extension.css
popup/messagepane.css
popup/optionspane.css
popup/popup.html
popup/popup.js
popup/replacepane.css

- Added a pane to the popup , triggered by CTRL-ALT-R
- Implemented functionality for replacing text using the regex feature
- Code refactors

Replace Text Feature

---

backend/backend.js
popup/popup.html
popup/popup.js

- Added two question mark icon images in popup, display none, with tooltip information
- Added script in popup that displays the icon for 3 seconds, or while the mouse hovers over the icon
- Added appropriate listener implementation in background script to issue an 'installed' action to the port when the onInstalled event is fired.

Tooltip on Install Update

---

backend/backend.js
popup/popup.js

- Addresses a couple of issues introduced by https://github.com/brandon1024/find/pull/157, notably the icon persisting in certain situations.

PATCH: Info Tooltip on Install

---

content/highlighter.js

- Ensure orange highlight class is added to all elements with the class `find-ext-occr#`

fixed seekHighlight()

---

content/content.js

- changed isInlineLevelElement() to use the element display property instead of referring to a list of element names with default inline display properties.

Display Property Support

---

manifest.json
manifest_firefox.json
popup/popup.html

- Updated manifests
- Modified README

V141 Pre Release Prep

---

content/highlighter.js
manifest.json
manifest_firefox.json

- Fixed a typo that caused the restoreClass() method to fail.

Highlight Seek Fix

---

content/content.js

- Minor bug fix that caused empty span elements to exist in the DOM, causing spacing and rendering issues.

Spacing Fix

---

.github/README.md
backend/backend.js
content/highlighter.js
popup/popup.js

- Implemented find-and-select feature.
- Triggered using the shortcut CTRL-SHIFT-ENTER
- Follows the first link that is highlighted with the orange highlight

Find and Select Feature

---

content/content.js

- Reverted change from c6ec3c06e59ce5957d1764ff9aaf3ceea561244b
- Added clause for node values of length 1 with charcode 10 (line feed)

Whitespace Issue Fix

---

.github/README.md

- . updated README: the keyboard settings moved to top left
- .
- .

the keyboard settings moved to top left

---

backend/backend.js
content/content.js
content/highlighter.js
lib/html-entity-handler/entityhandler.js
popup/popup.js

- Migrated code to ES6
- Minor code style fixes

Migrate Code to ES6

---

content/content.js
content/highlighter.css
content/highlighter.js

Fixes #206
https://developer.mozilla.org/docs/Web/CSS/all

Fix Inconsistent Style Between Activate and Deactivate Extension

---

manifest.json
manifest_firefox.json
popup/popup.js

- Ensure last search that is saved in local storage does not get populated into the search field in incognito mode.

Prevent Search Field History Population in Incognito Mode

---

popup/popup.js

Fixed minor bug that prevented the search field from obtaining focus when the extension is first installed.

Search Field Focus Fix

---

_config.yml

- removed _config.yml from master branch

Removed _config.yml

---

.gitignore
build.sh
manifest.json
manifest_firefox.json

- Created build script for packaging the extension for deployment in Chrome and Firefox
To package the extension:
```
./build.sh -m <path to manifest> -v <new version number> -o <build location>
```
Example:
```
./build.sh -m find/manifest.json -v 1.4.4 -o .build
```

Created Build Script

---

_locales/en/messages.json
background/background.js
content/highlighter.css
content/highlighter.js
manifest.json
manifest_firefox.json
popup/css/optionspane.css
popup/js/browser-action.js
popup/js/i18n.js
popup/js/options-pane.js
popup/js/storage.js
popup/popup.html

- Added hue, saturation and value sliders for changing the highlight colors
- Refactored the options logic into options-pane.js
- minor bug fixes

Highlight Color Feature

---

.github/README.md

- Added "users" count badge
- Added "last commit" badge
- Added "commits/year" badge

Added Badges to README

---

.github/README.md

- Removed commits/year badge
- Added firefox users count badge

Added Readme Badge for Firefox Users Count

---

.github/README.md

Reworked the content in the project README.md, and removed sections that
are no longer applicable, or are unnecessary.

Freshen README.md

---

app.js
background/background.js
background/browser-action-proxy.js
background/content-proxy.js
content/content.js
content/highlighter.js
content/parser.js
manifest.json
manifest_firefox.json

Refactored the content scripts to use app.js. In doing so, I was able to
resolve a bug that caused the auto search feature to not work. The
reason for this is because window.getSelection() was being called after
the dom representation object is constructed. This process inserts new
nodes into the DOM, so calling window.getSelection() will yield an empty
string.
Included in this commit are changes to the background-content message
action names.

Selected Text Auto Search Fix

---

.github/README.md

Replaced a missed SHIFT with the unicode character representing the
shift button. Also changed the contributors section, and added a license
section.

Minor Fixes to Readme

---

.github/README.md

This is patch release. It addresses an issue that caused the extension to fail to load properly in Firefox.
Release: Release Version 2.0.1
Code Name: Diophantine
Release Date: 02/14/2019
Contributors: Brandon Richardson (Brandon1024)
- #256 Firefox Bug Fix

Release v2.0.1 (public)

---

.github/README.md
_locales/en/messages.json
background/omni.js
popup/css/help.css
popup/css/savedexpressionspane.css
popup/css/searchpane.css
popup/help.html
popup/js/browser-action.js
popup/js/i18n.js
popup/js/options-pane.js
popup/js/saved-expressions-pane.js
popup/js/search-pane.js
popup/js/storage.js
popup/popup.html

Renamed History feature to Saved Expressions.

Rename 'History' Feature to 'Saved Expressions'

---

popup/css/extension.css
popup/css/optionspane.css
popup/css/searchpane.css

Adjusted the font size and face, and improved the search pane look and
feel.

Minor UI Improvements

---

popup/js/history.js
popup/js/saved-expressions-pane.js

This is a patch release. It addresses a few bugs that were discovered by members of the community.
Release: Release Version 2.1.1
Code Name: Fractal
Release Date: 26/12/2019
Contributors: @brandon1024
- #298 Fix Saved Expression Feature

Release Version 2.1.1 (public)

---

.github/README.md
popup/css/help.css
popup/help.html

- Removed Wiki section from README and help page
- Updated style and improved structure.

Updates to Help Page and README

---

background/omni.js

Make use of the defaultSuggestion omnibox API to display occurrence
counts and report errors.

Omnibox: Display Occurrence Count and Report Errors

---

.github/PRIVACY.md

- introduce a privacy statement to comply with chrome policies

add privacy statement

---

.github/PRIVACY.md

Release Version 2.2.1 (public):
Overview
This is a patch release. It introduces a privacy statement to comply with Chrome Web Store policies.
Release Information:
Release: Release Version 2.2.2
Code Name: Alif Null
Release Date: 09/09/2021
Contributors: @brandon1024
Issues Addressed:
Improvements:
#359 add privacy statement

Release Version 2.2.2 (public)
