- backend/backend.js
- content/content.js
- content/highlighter.js
- manifest.json
- popup/extension.css
- popup/popup.js
Added the `Use Strict` flag in all JS files to enforce defensive programming. Also removed useless `this.close()` from background script, and improved scrolling.
> Use Strict Flag to Enforce Defensive Programming

- content/content.js
Issue: https://github.com/brandon1024/find/issues/63
Previously, text that has the CSS property `display: none` or `display: hidden` were included in the DOM model object and were parsed by the regex search engine. This caused an issue because it would display occurrences of a regex that are not visible to the user.
These changes address that. Added a flag to the content script for building the model object that skips all elements (and children of elements) that have the display property none or hidden. Also modified preformatted flag to use a more rigorous check for css properties.
1. Testing Element Style: Loaded a web page, used the developer tools to find a container with some text and added the element style for `display: none`. Ran the extension, searching for text in the hidden …
> Search Text Only Visible on Page

- content/highlighter.js
Issue: #67 
Replaced our function for scrolling to an element with the native `scrollIntoView()` function. Although Chrome does not support options for smooth scrolling or setting an offset, it is the most reliable solution I have found thus far.
There is an issue logged for chrome to implement this behavior, so we may see this fixed in the next release of Chrome.
Chrome Issue [#648446](https://bugs.chromium.org/p/chromium/issues/detail?id=648446)
> Use Native Page Scrolling to Fix Scrolling Issues

- backend/backend.js
- content/content.js
- content/highlighter.js
- lib/html-entity-handler/entityhandler.js
- manifest.json
Issue: #64 
Implemented a HTML entity encoder/decoder content script that is injected into the webpage along with the content.js and highlighter.js. It is used to convert typical (and nontypical) HTML character entities to their ASCII character. 
Originally, characters that appear as their entity in text nodes would throw off the regex search, causing the entity to be interpreted as the entity code characters. 
The decoder is designed translates html character entities for codes `9, 10, 32-126, 160`. This represents all printable ASCII characters, and the non breaking space character.
The encoder only encodes characters the following characters used in HTML markup and formatting: `tab, newline, single quote, double quote, ampersand, <, >, non breaking space`.
This PR also addresses an …
> HTML Entity Decoding

- lib/html-entity-handler/entityhandler.js
While I was working on #64, I had not realized that HTML character entity names must appear exactly as described [here](https://dev.w3.org/html5/html-author/charref). I assumed that character names were case insensitive, but quickly realized that that was not the case.
This PR addresses this issue.
> HOTFIX: Entity Handler Case Sensitivity Fix

- content/content.js
- content/highlighter.js
Issue: #71 
When the `contents()` function is invoked on a jQuery object, it returns all children nodes to that object. However, when no children nodes exist, an empty object is returned. Invoking `unwrap()` on the contents will have no effect. This caused issues with highlighting, but more importantly left unwanted markup in the webpage after the extension is closed.
To fix this issue, I used the 'replaceWith()' function. If the contents of the jquery object is empty, the element will simply be removed from the DOM.
```
$el.replaceWith(function() {
return $(this).contents();
});
```
> Webpage Restoration Fix

- content/highlighter.js
Issue: #79
Currently, in `seekHighlight`, `window.scrollBy(0,-100);` is executed regardless of where the text is in the page. However, if a highlight appears in the bottom of the page, this should not be executed.
In this PR, I addressed this issue by conditionally executing the upwards scroll based on the position of the scrollbar after the `scrollIntoView()`.
> Scrolling to Text In Footer Fix

- backend/backend.js
- content/content.js
Issue: #77 
As mentioned in #77, using JavaScript performance profiling functions, I recorded that in a GitHub diff, our extension took on average 375ms to build the DOM model object. Digging deeper, I found that a large majority of this time is due to the fact that jQuery is used to wrap text nodes with our markup.
By replacing jQuery with vanilla JavaScript, `I was able to reduce 375ms down to around 189ms. This is a performance improvement of nearly 50%`.
Also as part of this PR, I moved the init action code in the background script to instead build the DOM model object when the extension first loads, i.e. when the background script receives an onConnect event. This improves the user-apparent performance/initial responsiveness.
> jQuery Performance Improvements

- manifest.json
Added the `offline_enable` flag to the manifest, which will allow the extension to be found when the Runs offline flag is set on the web store.
Testing can only be done when published.
> Chrome Web Store 'Runs Offline' Flag

- content/content.js
Excluded from the search any text that appears within the `Style` element. Also fixed a few bugs that affected certain hidden elements.
> Exclude Style Element from Search

- popup/extension.css
- popup/popup.html
- popup/popup.js
Added a small exclamation icon in place of the index text when a malformed regex is entered. Hovering over the icon will display a small tooltip with information to the user.
> Regex Error Icon/Notification

- popup/popup.html
- popup/popup.js
If you open the native tool and the search field is empty, the seek buttons are disabled. In our extension, the buttons used to be enabled when the extension opens. This PR addresses this issue by ensuring that the seek buttons are disabled by default if there is no text in the search field.
If the search field contains text (from previous search), the native tool seek buttons are enabled and clicking them will show the index text and highlight if the text appears in the page. In our extension, if the search field contained the last search, clicking the buttons has no effect. Now, clicking the seek buttons will invoke the update action if needed.
> Usability Inconsistency with Native Tool

- popup/popup.js
Added exception to URL rule to prevent the error message from being displayed when opening the extension in chrome://newtab/.
> Allow Extension in chrome://newtab/

- backend/backend.js
When a user installs the extension, the currently opened tabs must be reloaded to reinject the content scripts. A user with limited knowledge of the inner workings of chrome extensions will believe that the extension is broken.
The changes as part of this PR are to inject the pages on the onInstalled event.
> Inject Content Scripts on Install

- popup/popup.html
Occasionally, as the user types text into the search field, the field provides autocomplete suggestions. However, the drop down is clipped and not useful.
This PR addresses the issue by removing the autocomplete feature completely.
> Remove Search Field Autocomplete

- popup/extension.css
- popup/popup.html
- popup/popup.js
Our extension is limited to working only in web pages and text files. The extension is not able to search through PDF files.
It would be beneficial to display a small message to the user if they try to use the extension while viewing a page with the url ending in .PDF, similar to the message for loading the extension in the chrome:// namespace.
- Added a PDF fileview limitation message in the popup, triggered by urls ending in `.pdf`
> Show Message for URLs Ending with .PDF

- content/content.js
- popup/messagepane.css
- popup/popup.html
- popup/popup.js
- When using the extension in offline web pages, the extension will not highlighting results on the page if the `Allow extension in file URLs` checkbox is not enabled in chrome extension settings. This can be misleading and cause the user to believe the extension is broken.
- To mitigate this issue, I have added a check in the popup script to check if the scripts are loaded in a `file://` URL. An error icon and tooltip is shown with more information.
> Offline File Search Error Message

- content/content.js
- Added special clause in `isInlineLevelElement(node)` to treat the `<br/>` element as a block level element instead of inline. This ensures that text that is broken into paragraphs with the break element will correctly highlight and match text.
Tested on https://www.senate.gov/legislative/LIS/roll_call_lists/roll_call_vote_cfm.cfm?congress=115&session=1&vote=00195 with regex `D.*Yea`
> Treat <br/> as Block Element

- backend/backend.js
- popup/popup.html
- popup/popup.js
- Added UI slider in options pane for enabling persistent highlights
- Implemented logic in background script to only restore highlights if option is disabled
- Added highlight restore at port connect to remove any highlights that may have existed in the DOM on extension open (used to easily remove persisted highlights on extension open without the need to reload the page)
> Persistent Highlight Feature

- backend/backend.js
- content/highlighter.js
- manifest.json
- manifest_firefox.json
- Implemented Omnibox support
- Typing `find` and pressing `TAB` will allow you to type a regular expression in the bar and highlight occurrences on the page
- Pressing enter will remove the extension markup, but leave the highlights.
- To remove the highlights, reload the page or type `find` in the omnibox and press `TAB`.
> Omnibox Support

- content/content.js
- Added textarea element to node filter
- The extension was processing the textarea element and placing a span element inside the element, which caused it to not display text at all.
> Text Area Text Bug Fix

- backend/backend.js
Fixed bug that cause the content script autoinjection feature to break on firefox when the extension is first installed.
The reason this was occurring was because content scripts are automatically injected into existing pages in Firefox, but not in Chrome. Therefore, the autoinjection code was causing issues with duplicate injections in Firefox.
Added a simple check to make sure that the code is skipped in firefox.
> Content Script Autoinjection Bug Fix

- popup/js/options-pane.js
In options-pane.js, in the adaptOptions function, there is a small bug
that causes the hex colour codes for index and all highlights to be
swapped, only when the options object is not pulled from local storage.
This commit addresses that issue.
> Fix Inconsistent Options On First Install

- background/background.js
- background/content-proxy.js
- content/content.js
- content/highlighter.js
- manifest.json
- manifest_firefox.json
- popup/js/browser-action.js
To ensure that the chrome extension state can be recovered when the
extension closes unexpectedly, added index and regex state variables in
the highlighter content script. On extension start, load their values
and restore state if not null.
Also migrated the content scripts to use the new app.js, and fixed a
minor issue that caused the follow link feature to not work correctly.
> Persist Query State on Extension Close

- _locales/en/messages.json
- background/background.js
- content/highlighter.js
- popup/js/browser-action.js
- popup/js/search-pane.js
- popup/popup.html
Added a warning icon to the search pane notification area that is
flashed when an iframe is encountered in the page. This is used to
indicate to the user that it's likely that some occurrences of their
search query will not be highlighted in the page.
In the future, when traversing same-origin iframes is implemented,
this will be adapted to only show warnings when iframes that are
not on the same origin are encountered.
In this commit, some logic was moved from the browser action namespace
into the search pane namespace to improve cohesion. Some logic was also
removed to utilize already existing logic.
> Iframe Warning Icon

- app.js
In v2.0.0, the extension won't open in Firefox due to a bug in app.js
that causes the window.chrome namespace to be used rather than the
window.browser namespace. Firefox supports both namespaces, and because
of this, the wrong namespace was being used.
> Firefox Bug Fix

- build.sh
Prevented build script from adding the build script to the build
artifacts.
> Updated Build Script to Skip build.sh

- background/omni.js
In v2, the omni.js used default options and disregarded the
user-configured options through the options pane. Some users have asked
whether they could use the configured options through the omnibox, so I
have opted to allow it.
Rather than replicate the storage mechanism between the popup and
background, I implemented a custom storage access function in the omni
namespace for accessing options. It's not perfect, there's some code
duplication here, but it's better than the alternative.
> Allow Options through Omnibox

- .github/README.md
> In version 1.4.0, we introduced omnibox support! This allows you to highlight text on a page without even opening the extension. To use this feature, type find in your browser's address bar, **press TAB**, and then enter a regular expression. Occurrences of the regular expression will become highlighted on the page as you type.
Pressing tab just moves to the popup menu of the address bar, selecting the first url item.
It seems to me it is wrong description. 
The correct way is: Type find. **Press space**, and then enter a regular expression.
> Correction of description

- _locales/en/messages.json
- background/omni.js
- popup/css/extension.css
- popup/css/searchpane.css
- popup/js/options-pane.js
- popup/js/search-pane.js
- popup/popup.html
Implemented two new options which allow the options/history toggle
buttons in the search pane to be hidden. The panes may still be toggled
using the keyboard shortcuts.
> Option to Hide Options/History Buttons

- background/background.js
- background/browser-action-proxy.js
- background/omni.js
When switching tabs with the extension open and a search in progress,
highlights injected into the page are not removed as expected. To fix
this, tab queries for the current active tab were removed and tabs were
only querried when the browser action port is established.
> Switch Tabs Highlights Fix

- background/browser-action-proxy.js
- popup/js/browser-action.js
- popup/js/history.js
- popup/js/replace-pane.js
- popup/js/storage.js
- popup/popup.html
Created a new interface for retrieving and persisting search query
information for specific hosts. This is used to populate the search
field with the last search query for the current host.
This revision also addresses the extension popup slowness during
initialization. Browser initialization and page tokenization was
conflicting, where parsing the DOM was computationally expensive and
slowing down the initialization response to the browser action. Now, the
browser action is more responsive.
> Implemented Host-Specific History for Persisting Latest Search Queries

- content/highlighter.js
Prior to this revision, seeking to the next or previous occurrent would
scroll the page regardless of whether the occurrence was in the current
viewport or not. This was frustrating for some users, so I improved the
logic to check if the next/previous element is in the viewport before
scrolling.
> Improvements to Scrolling When Seeking

- _locales/en/messages.json
- popup/help.html
- popup/js/options-pane.js
When installing the extension for the first time, the "Hide Copy To
Clipboard Button" is disabled, so the button is incorrectly shown by default.
This is due to the defective adaptOptions() function.
Fixed adaptOptions, and also updated the help page to add info on this
option.
> Ensure Clipboard Button Hidden by Default

- popup/img/icon/copy-to-clipboard-line.svg
- popup/js/saved-expressions-pane.js
An incorrect source path for the bookmark icon was preventing the icon
from loading in the saved expressions pane.
> Fix Bookmark Icon Source Path

- popup/js/history.js
- popup/js/saved-expressions-pane.js
The saved expressions feature was failing to save new entries because
the data is not updated correctly. If the saved expressions did not
exist in local storage, nothing would be saved.
Also addressed a minor issue that caused an undefined callback to be
executed, which would throw an error.
> Fix Saved Expression Feature

- _locales/en/messages.json
- content/highlighter.js
- popup/popup.html
Similar to the native tool, highlighted text is now colored black to
improve accessibility (constrast with highlight color).
- highlighted text is now colored black for better contrast.
- minor improvements to options pane.
> F311: Improve Accessibility for Text Color in Highlights

- background/background.js
- background/browser-action-proxy.js
- content/content.js
- popup/js/browser-action.js
* F325: Correct UpdateSearch for Fetch Document Representation if Unset
When the popup is opened with a saved search, pressing enter had no
effect. This has been corrected. The updateSearch function would return
if the DOM representation is missing, but the representation was never
set.
* F323: Correct Page Index Cache
We used to remember the search index in the page if the extension is
reopened, but there was a defect that would prevent this from working
properly (always set to 0).
* F309: Race Condition for Extension Initialization
There was a race condition that would cause the extension to fail to
load. This has been corrected.
> Various Fixes and Improvements

- manifest.json
- manifest_firefox.json
- updated manifest to remove the clipboardWrite permission
The extension was removed by Google because of this extra permission. Will redeploy.
> F355: Remove clipboardWrite Permission
